AWSTemplateFormatVersion: '2010-09-09'

# Parameters:
  # Domain:
  #   AllowedPattern: ^(\*\.)?(((?!-)[A-Za-z0-9-]{0,62}[A-Za-z0-9])\.)+((?!-)[A-Za-z0-9-]{1,62}[A-Za-z0-9])$
  #   ConstraintDescription: must not begin or end with a period
  #   Type: String
  # HostedZoneId:
  #   Description: The hosted zone id of the domain.
  #   Type: String

Resources:

  # WebsiteUrl:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     AliasTarget:
  #       DNSName: !GetAtt WebsiteDistribution.DomainName
  #       HostedZoneId: Z2FDTNDATAQYW2 # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html#cfn-route53-aliastarget-hostedzoneid
  #     HostedZoneId: !Ref HostedZoneId
  #     Name: !Ref Domain
  #     Type: A

  WebsiteBucket:
    Type: AWS::S3::Bucket
  WebsiteBucketOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Website Bucket CloudFront Origin Access Identity
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Sid: "Grant a CloudFront Origin Identity access to support private content"
            Action:
              - s3:GetObject
            Effect: "Allow"
            Resource: !Sub ${WebsiteBucket.Arn}/*
            Principal:
              CanonicalUser: !GetAtt WebsiteBucketOAI.S3CanonicalUserId

  WebsiteDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        # Aliases:
        #   - !Ref Domain
        CustomErrorResponses:
          - ErrorCode: 404
            ResponsePagePath: /index.html
            ResponseCode: 200
            ErrorCachingMinTTL: 30
          - ErrorCode: 403
            ResponsePagePath: /index.html
            ResponseCode: 200
            ErrorCachingMinTTL: 30
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          DefaultTTL: 0
          ForwardedValues:
            QueryString: false
          MaxTTL: 0
          MinTTL: 0
          TargetOriginId: !Sub ${AWS::StackName}:${WebsiteBucket}:S3Origin
          ViewerProtocolPolicy: redirect-to-https
        # Logging:
        #   Bucket: a
        #   Enabled: true
        #   IncludeCookies: false
        #   Prefix: a
        Enabled: true
        Origins:
          - DomainName: !GetAtt WebsiteBucket.DomainName
            Id: !Sub ${AWS::StackName}:${WebsiteBucket}:S3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${WebsiteBucketOAI}
        # Tags:
        # - Key: string-value
        #   Value: string-value
        # ViewerCertificate:
        #   AcmCertificateArn: !Ref WebsiteCert
        #   MinimumProtocolVersion: TLSv1.1_2016
        #   SslSupportMethod: sni-only

  # WebsiteCert:
  #   Type: AWS::CertificateManager::Certificate
  #   Properties:
  #     DomainName: !Ref Domain

Outputs:
  FrontendUrl:
    Value: !Sub https://${WebsiteDistribution.DomainName}
  SourceS3Uri:
    Value: !Sub s3://${WebsiteBucket}