name: Deploy the game

on: [push]

jobs:
  deploy:
    env:
        AWS_CFN_STACK_NAME: ggj2021
        AWS_CFN_DOMAIN: ggj2021.charlieguse.com
    name: Publish to S3
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testing run-script-os with Node.js ${{ matrix.node-version }} on ${{ matrix.os }} from a tests project similar to how run-script-os is used by others.
        uses: actions/setup-node@v2
      - name: Install node_modules
        run: npm ci
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.AWS_CFN_STACK_NAME }}
          template: template.yaml
          parameter-overrides: "Domain=${{ env.AWS_CFN_DOMAIN }},HostedZoneId=${{ secrets.HOSTED_ZONE_ID }}"
          no-fail-on-empty-changeset: "1"
      - name: Build Assets
        run: npm run build
      - name: Deploy Assets
        run: |
          S3URI=$(aws cloudformation describe-stacks --stack-name ${AWS_CFN_STACK_NAME} --query "Stacks[*].Outputs[?OutputKey=='SourceS3Uri'].OutputValue" --output text)
          aws s3 sync ./dist ${S3URI} --delete
      - name: CloudFront Url
        run: |
          URL=$(aws cloudformation describe-stacks --stack-name ${AWS_CFN_STACK_NAME} --query "Stacks[*].Outputs[?OutputKey=='FrontendUrl'].OutputValue" --output text)
          echo $URL
      - name: Hosted Domain Url
        run: |
          echo https://${{ env.AWS_CFN_DOMAIN }}